ci:
  autofix_prs: true
  skip: [pixi-lock-check]

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v6.0.0
    hooks:
      - id: check-added-large-files
        args: [--maxkb=8192]
      - id: check-merge-conflict
      - id: check-yaml
        args: [--allow-multiple-documents]
      - id: end-of-file-fixer
        exclude: "tests/cis_tests/.*"
      - id: trailing-whitespace
        exclude: "tests/cis_tests/.*"

  - repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.12.11
    hooks:
      - id: ruff-check
        args: [--fix, --exit-non-zero-on-fix]
        exclude: "tests/cis_tests/.*"
      - id: ruff-format
        exclude: "tests/cis_tests/.*"

  - repo: local
    hooks:
      - id: pixi-lock-check
        name: pixi-lock-check
        entry: bash -c "PATH=$HOME/.pixi/bin:$PATH pixi lock --check"
        stage: pre-push
        language: system
