name: mr_reduction
channels:
  - mantid/label/main
  - conda-forge
  - oncat
dependencies:
  - python>=3.10
  - argcomplete
  - flask
  - gunicorn
  - mantidworkbench=6.10
  - neutrons::finddata=0.10
  - pandas
  - pip
  - plotly
  - pyoncat
  - versioningit
  # -- Development and documentation
  - anaconda-client
  - boa
  - conda-build < 4  # conda-build 24.x has a bug, missing update_index from conda_build.index
  - conda-verify
  - libarchive
  - libmamba
  - pre-commit
  - pytest
  - pytest-cov
  - pytest-xdist
  - python-build
  - setuptools
  - sphinx
  - sphinx-rtd-theme
  - furo
