name: mr_reduction
channels:
  - mantid/label/main
  - conda-forge
dependencies:
  - python>=3.10
  - versioningit
  - mantidworkbench=6.9
  - pandas
  - plotly
  # -- Development dependencies
  - pre-commit
  - sphinx
  - sphinx-rtd-theme
  - libmamba
  - libarchive
  - anaconda-client
  - boa
  - conda-build < 4  # conda-build 24.x has a bug, missing update_index from conda_build.index
  - conda-verify
  - python-build
  - pytest
  - pytest-cov
  - pytest-xdist
  - pip
