name: conda packaging and deployment

on:
  workflow_dispatch:
  push:
    branches: [qa, main]
    tags: ['v*']

jobs:
  linux:
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash -l {0}
    steps:
      - uses: actions/checkout@v3
      - uses: conda-incubator/setup-miniconda@v2
        name: Setup Conda
        with:
          auto-update-conda: true
          channels: mantid/label/main,conda-forge,defaults
          miniforge-version: latest
          environment-file: environment.yml
      - name: Create Conda Environment
        run: |
          echo "Creating the Conda environment explicitly to ensure it exists"
          mamba env create --file environment.yml --force
      - name: build conda package
        run: |
          # set up environment
          cd conda.recipe
          echo "versioningit $(versioningit ../)"
          # build the package
          CHANNELS="--channel mantid/label/main --channel conda-forge --channel oncat --channel neutrons"
          VERSION=$(versioningit ../) conda mambabuild $CHANNELS --output-folder . .
          conda verify noarch/mr_reduction*.tar.bz2
      - name: upload conda package to anaconda
        shell: bash -l {0}
        if: startsWith(github.ref, 'refs/tags/v')
        env:
          ANACONDA_API_TOKEN: ${{ secrets.ANACONDA_TOKEN }}
          IS_RC: ${{ contains(github.ref, 'rc') }}
        run: |
          # label is main or rc depending on the tag-name
          CONDA_LABEL="main"
          if [ "${IS_RC}" = "true" ]; then CONDA_LABEL="rc"; fi
          echo pushing ${{ github.ref }} with label $CONDA_LABEL
          anaconda upload --label $CONDA_LABEL conda.recipe/noarch/mr_reduction*.tar.bz2
